"use client";
import { useState } from "react";
export type RainEffect = { id: string; polygon: [number, number][]; intensity: number; water_mm: number; affected_assets: number; electricity_uplift_percent: number; road_delay_factor: number; metro_demand_index: number };
export default function RainControls({ drawing, points, zones, busy, onDraw, onClear, onApply, onChange, onRemove }: { drawing: boolean; points: number; zones: RainEffect[]; busy: boolean; onDraw: () => void; onClear: () => void; onApply: (intensity: number) => void; onChange: (id: string, intensity: number) => void; onRemove: (id: string) => void }) {
  const [intensity, setIntensity] = useState(60);
  return <section className="electric-panel rain-controls"><h2>Rainfall area & cross-system effects</h2><p>Draw an area on the map, choose rainfall intensity, then run the simulation. The polygon affects street travel costs and synthetic loads inside it.</p>
    <button disabled={busy || drawing} onClick={onDraw}>{drawing ? `Drawing · ${points} points` : "Draw rainfall polygon"}</button><button disabled={busy || !points} onClick={onClear}>Clear drawing</button>
    <label>Rain intensity · {intensity} mm/hour<input aria-label="Rain intensity" type="range" min="0" max="150" step="5" value={intensity} onChange={e => setIntensity(Number(e.target.value))} /></label>
    <button disabled={busy || points < 3} onClick={() => onApply(intensity)}>Apply rainfall to polygon</button>
    {drawing && <p role="status">Click at least three corners on the map below, then apply rainfall. Avoid crossing the polygon edges.</p>}
    {zones.map((z,index) => <article className="rain-zone" key={z.id}><h3>Rain area {index+1} · {z.affected_assets} modeled assets</h3><label>Area {index+1} intensity<select aria-label={`Area ${index+1} intensity`} value={z.intensity} disabled={busy} onChange={e => onChange(z.id, Number(e.target.value))}>{[...new Set([0,10,30,60,100,150,z.intensity])].sort((a,b) => a-b).map(n => <option key={n} value={n}>{n} mm/hour{n===0 ? " · rain stopped" : ""}</option>)}</select></label><div className="rain-impacts"><p><strong>Electricity +{z.electricity_uplift_percent}%</strong><br />Modeled pumping and local demand uplift</p><p><strong>Road travel ×{z.road_delay_factor}</strong><br />Delay on roads intersecting this polygon</p><p><strong>Metro demand index {z.metro_demand_index}</strong><br />100 = baseline; modeled shift from road travel</p></div><p>Accumulated surface-water proxy: {z.water_mm.toFixed(3)} mm</p><button disabled={busy} onClick={() => onChange(z.id,0)}>Stop rain; allow drainage</button><button disabled={busy} onClick={() => onRemove(z.id)}>Remove area and its effects</button></article>)}
    <p className="muted">Synthetic assumptions: 8 mm/hour drainage; electricity uplift capped at 35%; road delay capped at 2.5×; metro demand index capped at 180. No measured flood depth, rainfall feed, metro passenger counts or calibrated drainage model. Overlapping road/electric effects use the strongest area.</p>
  </section>;
}
