"use client";
import {useEffect,useRef,useState} from "react";
import {request} from "@/lib/api";
import type {MetroSnapshot} from "./MetroMap";
type Station={id:string;name:string};
type Network={line_stations:Record<string,Station[]>;routes:{route_id:string;route_color:string}[]};
export default function MetroSchematic({data}:{data:MetroSnapshot|null}){
 const [network,setNetwork]=useState<Network|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState("");
 useEffect(()=>{let alive=true;request<Network>("/metro/network").then(value=>{if(alive)setNetwork(value);}).catch(()=>{if(alive)setError("Metro network unavailable");});return()=>{alive=false;};},[]);
 const [seconds,setSeconds]=useState(0);
 const clock=useRef({seconds:0,wall:0,target:0,received:0,running:false,speed:1,key:""});
 useEffect(()=>{if(!data)return;const c=clock.current,now=performance.now();
 const key=`${data.version}:${data.state.sim_seconds}:${data.state.running}:${data.state.speed}`;
 if(key===c.key)return;
 const incoming=data.state.sim_seconds;
 if(!c.key||!data.state.running||Math.abs(incoming-c.seconds)>Math.max(60,10*data.state.speed))c.seconds=incoming;
 c.target=incoming;c.received=now;c.wall=now;c.running=data.state.running;c.speed=data.state.speed;c.key=key;
 },[data]);
 useEffect(()=>{let frame=0,lastPaint=0;const tick=(now:number)=>{const c=clock.current;
 const dt=Math.min(.1,Math.max(0,(now-c.wall)/1000));c.wall=now;
 if(c.running&&now-c.received<5000){const target=c.target+(now-c.received)/1000*c.speed;
 const correction=Math.max(-.2*c.speed,Math.min(.2*c.speed,(target-c.seconds)*.5));
 c.seconds+=dt*(c.speed+correction);}
 if(now-lastPaint>=32){setSeconds(c.seconds);lastPaint=now;}frame=requestAnimationFrame(tick);};
 frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
 const [zoom,setZoom]=useState(1);
 const [view,setView]=useState<"pdf"|"schematic">("pdf");

 const coordinates:Record<string,[number,number][]>= {
 RED:[[184,294],[276,295],[326,344],[373,392],[418,436],[461,481],[502,521],[547,566],[594,613],[639,658],[639,731],[639,816],[639,875],[682,936],[722,990],[762,1049],[802,1109],[844,1169],[886,1232],[982,1232],[1103,1232],[1170,1232],[1245,1232],[1325,1232],[1429,1232],[1494,1296],[1494,1366]],
 BLUE:[[1494,937],[1456,898],[1415,855],[1373,813],[1331,772],[1290,731],[1213,731],[1126,731],[982,731],[892,731],[828,731],[758,731],[691,731],[639,731],[536,731],[464,731],[384,731],[317,731],[280,699],[241,658],[206,621],[163,580],[81,494]],
 GREEN:[[982,1232],[982,1156],[982,1101],[982,1047],[982,993],[982,936],[982,882],[982,828],[982,660]]
 };
 if(view==="schematic")for(const [row,id] of ["RED","BLUE","GREEN"].entries())coordinates[id]=(network?.line_stations[id]??[]).map((_,i,stations)=>[80+i*1440/Math.max(1,stations.length-1),160+row*250]);
 const turnbacks=(data?.turnbacks??[]).filter(t=>t.phase||seconds<t.ends_at_seconds);
 const timer=(n:number)=>{const whole=Math.max(0,Math.ceil(n));return `${Math.floor(whole/60)}:${String(whole%60).padStart(2,"0")}`;};
 const departureTime=(n:number|null)=>n===null?'Unassigned':`${String(Math.floor(n/3600)).padStart(2,"0")}:${String(Math.floor(n%3600/60)).padStart(2,"0")}:${String(Math.floor(n%60)).padStart(2,"0")}`;
 const shared=new Map<string,[number,number][]>();
 for(const [id,points] of Object.entries(coordinates))(network?.line_stations[id]??[]).forEach((station,i)=>{if(points[i])shared.set(station.id,[...(shared.get(station.id)??[]),points[i]]);});
 return <div className="metro-schematic"><div role="group" aria-label="Metro map view" style={{display:"flex",gap:12,marginBottom:16}}><button aria-pressed={view==="pdf"} onClick={()=>{setView("pdf");setZoom(1);}}>PDF map</button><button aria-pressed={view==="schematic"} onClick={()=>{setView("schematic");setZoom(1);}}>Schematic map</button></div><p>{view==="pdf"?"PDF NETWORK MAP":"SCHEMATIC NETWORK MAP"} · train movement follows the shared operating model · green: at station · yellow: travelling · turnbacks: operational countdowns · bay positions are schematic</p>{error&&<p role="alert">{error}</p>}<div style={{display:"flex",gap:12,alignItems:"center",marginBottom:12}}><button onClick={()=>setZoom(Math.max(1,zoom-0.5))} disabled={zoom===1}>Zoom out</button><strong>{Math.round(zoom*100)}%</strong><button onClick={()=>setZoom(Math.min(3,zoom+0.5))} disabled={zoom===3}>Zoom in</button><span>{data?.trains.filter(t=>t.status==="IN_TRANSIT").length??0} trains moving · {data?.trains.filter(t=>t.status==="DWELLING").length??0} at stations · {data?.state.speed??1}× simulation speed</span></div><section className="metro-turnback-desk" aria-label="Train turnback countdowns"><h3>Turnback · {turnbacks.length} trains waiting</h3><p>Entry into bay → cab change → return to platform. Release waits for crew readiness, assigned service and track clearance. Bay locations are model assumptions.</p>{turnbacks.length?<div className="metro-turnback-list">{turnbacks.map(t=><article key={t.id}><div><strong>{t.station}</strong><span>{t.line_id} · {t.block}</span></div><strong className="metro-turnback-timer" aria-label={`${t.block} turnback remaining`}>{timer(t.ends_at_seconds-seconds)}</strong><small>{t.phase?.replaceAll("_"," ")} · {t.crew_ready===false?"Awaiting pilot readiness":"Crew ready"}<br/>remaining of {timer(t.duration_seconds)} reversing cycle<br/>Next departure {departureTime(t.next_departure_seconds)} IST → {t.next_destination}</small></article>)}</div>:<p>No active train turnbacks at the current simulation time.</p>}{!!data?.turnback_quality?.overlapping_trip_pairs&&<small role="status">Timetable quality: {data.turnback_quality.overlapping_trip_pairs} source trip conflicts are recorded. The operating model uses a separate finite-fleet assignment; original source records remain unchanged.</small>}</section><div style={{overflow:"auto",maxHeight:900}}><svg viewBox={view==="pdf"?"-40 175 1680 1500":"-120 0 1840 1050"} role="img" aria-label="Hyderabad metro schematic network" style={{width:`${zoom*100}%`,minWidth:1050,background:"#ffffff"}}>
 {view==="pdf"?<image href="/metro-network-reference.png" x={0} y={0} width={1600} height={1600}/>:<g>{[...shared].filter(([,points])=>points.length>1).map(([id,points])=><path key={id} d={`M${points[0].join(",")} L${points[1].join(",")}`} stroke="#7993a3" strokeWidth={1.5} strokeDasharray="5 6"/>)}</g>}
 {Object.entries(coordinates).map(([id,points])=>{const stations=network?.line_stations[id]??[];const color="#"+(network?.routes.find(r=>r.route_id===id)?.route_color??"888888");return <g key={id}>
 {view==="schematic"&&points.length>0&&<g><text x={50} y={points[0][1]-105} fill={color} fontSize={22} fontWeight="bold">{id} LINE</text><text x={50} y={points[0][1]-70} fill="#243951" fontSize={16}>{stations[0]?.name} ↔ {stations.at(-1)?.name}</text>{[-24,24].map(offset=><polyline key={offset} points={points.map(p=>`${p[0]},${p[1]+offset}`).join(" ")} fill="none" stroke={color} strokeWidth={3} opacity={.8}/>)}{stations.map((station,i)=><g key={station.id}><circle cx={points[i][0]} cy={points[i][1]} r={(shared.get(station.id)?.length??0)>1?10:6} fill="#ffffff" stroke={(shared.get(station.id)?.length??0)>1?"#334b61":color} strokeWidth={3}/><text transform={`translate(${points[i][0]},${points[i][1]+30}) rotate(48)`} fill="#30475e" fontSize={13}>{station.name}</text></g>)}</g>}
 {points.length>0&&[0,points.length-1].map((index,end)=>{const terminal=points[index];const pdfBays:Record<string,[number,number][]>= {RED:[[184,235],[1500,1490]],BLUE:[[1500,1070],[80,365]],GREEN:[[1100,1360],[1100,595]]};const bay:[number,number]=view==="pdf"?pdfBays[id][end]:[terminal[0]+(end?75:-75),terminal[1]];const name=stations[index]?.name??id;return <g key={`turnback-${end}`} className="metro-turnback" role="button" tabIndex={0} aria-label={`${name} turnback area`} onClick={()=>setSelected(`${name} turnback area: proposed simulation facility, not an official GTFS station. Countdowns use the shared reversing phases. Bay positions and crew-task durations are model assumptions.`)}><path d={`M${terminal.join(",")} L${bay.join(",")}`} fill="none" stroke={color} strokeWidth={4} strokeDasharray="6 5"/><rect x={bay[0]-16} y={bay[1]-14} width={32} height={28} rx={5} fill="#142b3b" stroke={color} strokeWidth={3}/><text x={bay[0]} y={bay[1]+6} textAnchor="middle" fill="white" fontSize={23}>↶</text><rect x={bay[0]-60} y={bay[1]+19} width={120} height={33} rx={4} fill="#142b3b"/><text x={bay[0]} y={bay[1]+32} textAnchor="middle" fill="white" fontSize={11}>TURNBACK</text><text x={bay[0]} y={bay[1]+45} textAnchor="middle" fill="#a9c2d2" fontSize={10}>Schematic bay</text>{turnbacks.filter(t=>t.line_id===id&&t.station_id===stations[index]?.id).map(t=>{const elapsed=Math.max(0,seconds-t.started_at_seconds),fraction=elapsed<30?elapsed/30:elapsed<150?1:Math.max(0,1-(elapsed-150)/30);return <g key={`movement-${t.id}`} transform={`translate(${terminal[0]+(bay[0]-terminal[0])*fraction},${terminal[1]+(bay[1]-terminal[1])*fraction})`}><rect x={-9} y={-13} width={18} height={26} rx={4} fill="#f5bc44" stroke="#263b54" strokeWidth={2}/><title>{t.block} · {t.phase} · simulated reversing</title></g>;})}{turnbacks.filter(t=>t.line_id===id&&t.station_id===stations[index]?.id).map((t,n)=><g key={t.id} transform={`translate(${bay[0]},${bay[1]+70+n*55})`} data-turnback-id={t.id} role="img" aria-label={`${t.block} at ${name} turnback, ${timer(t.ends_at_seconds-seconds)} remaining`}><rect x={-95} y={-12} width={190} height={48} rx={6} fill="#fff7dc" stroke="#9b6a0d" strokeWidth={2}/><text x={0} y={5} textAnchor="middle" fill="#65410b" fontSize={12}>{t.block} · ↶ TURNBACK</text><text x={0} y={26} textAnchor="middle" fill="#5c3c06" fontSize={19} fontWeight="bold">{timer(t.ends_at_seconds-seconds)}</text></g>)}</g>;})}
 {stations.map((station,i)=>points[i]&&<circle key={station.id} cx={points[i][0]} cy={points[i][1]} r={18} fill="transparent" role="button" tabIndex={0} aria-label={`${station.name} station on ${id}`} style={{cursor:"pointer"}} onClick={()=>setSelected(station.name)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(station.name);}}}><title>{station.name}</title></circle>)}
 {data?.trains.filter(t=>t.line_id===id).map(train=>{

 const timetable=train.schedule??[];
 const leg=timetable.findIndex((stop,i)=>seconds>=stop.arrival&&seconds<(timetable[i+1]?.arrival??stop.departure));
 if(!train.motion&&leg<0)return null;
 const stop=train.motion?{station:train.from_station,departure:Math.max(train.dwell_until??seconds,train.hold_until??0),arrival:seconds}:timetable[leg];
 const next=train.motion?{station:train.to_station,arrival:seconds+train.seconds_to_next,departure:seconds+train.seconds_to_next}:timetable[Math.min(leg+1,timetable.length-1)];
 const a=stations.findIndex(s=>s.name===stop.station),b=stations.findIndex(s=>s.name===next.station);
 if(a<0||b<0||!points[a]||!points[b])return null;
 const elapsed=Math.min(2,Math.max(0,seconds-(data?.state.sim_seconds??seconds)));
 const progress=train.motion?(train.status==='DWELLING'?0:Math.min(.999,train.progress+(train.speed_mps??0)*elapsed/Math.max(1,train.segment_m??1))):(seconds<stop.departure?0:Math.min(1,(seconds-stop.departure)/Math.max(1,next.arrival-stop.departure)));
 const tx=points[a][0]+(points[b][0]-points[a][0])*progress;
 const ty=points[a][1]+(points[b][1]-points[a][1])*progress+(view==='schematic'?(b>=a?-24:24):0);
 const status=train.motion?train.status:(seconds<stop.departure?'DWELLING':'IN_TRANSIT');
 const detail=status==="DWELLING"?`${train.id} at ${stop.station} · departs in ${Math.max(0,Math.ceil(stop.departure-seconds))} seconds (subject to clearance)`:`${train.id}: ${stop.station} → ${next.station} · ${status}`;
 return <g key={train.id} className="schematic-train" data-train-id={train.id} data-position={`${tx},${ty}`} data-status={status} transform={`translate(${tx},${ty})`} role="button" tabIndex={0} aria-label={`${train.id} simulated train`} style={{cursor:"pointer"}} onClick={()=>setSelected(detail)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(detail);}}}>{status==="DWELLING"&&<g className="metro-dwell-highlight"><circle r={23} fill="#28dc9e" fillOpacity={0.25} stroke="#007e54" strokeWidth={3}/><rect x={-66} y={-48} width={132} height={25} rx={5} fill="#075e43" stroke="white"/><text x={0} y={-31} textAnchor="middle" fill="white" fontSize={12} fontWeight="bold">AT STATION · {train.release===false||train.crew_ready===false?"WAIT CREW":`${Math.max(0,Math.ceil(stop.departure-seconds))}s`}</text></g>}<circle r={19} fill={status==="DWELLING"?"#28dc9e":"#ffdf72"} fillOpacity={0.65}/><rect x={-9} y={-13} width={18} height={26} rx={5} fill="#102b40" stroke="white" strokeWidth={2}/><rect x={-5} y={-8} width={10} height={9} rx={2} fill={color}/><circle cx={-4} cy={7} r={2} fill="white"/><circle cx={4} cy={7} r={2} fill="white"/><title>{detail} · simulated operating state</title></g>;
 })}</g>;})}
 </svg></div>{selected&&<p className="metro-station-detail">{selected}</p>}</div>;
}
