"use client";
import {useEffect,useState} from 'react';
import {request} from '@/lib/api';
type Runs={active_id:string;runs:{id:string;name:string;status:string;sim_seconds:number;service_date:string}[];note:string};
export default function MetroServiceDays(){
 const [data,setData]=useState<Runs|null>(null),[actor,setActor]=useState(''),[name,setName]=useState('Metro review checkpoint'),[day,setDay]=useState(''),[source,setSource]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{request<Runs>('/metro/service-days').then(setData).catch(()=>setError('Service-day list unavailable'));},[]);
 const act=async(action:string)=>{setBusy(true);setError('');try{setData(await request<Runs>('/metro/service-days',{method:'POST',body:JSON.stringify({action,actor,name,source_id:source||null,service_date:day||null,request_id:crypto.randomUUID()})},60000));}catch(e){setError(e instanceof Error?e.message:'Run not changed');}finally{setBusy(false);}};
 return <details className="metro-operations-v3"><summary>Service days, checkpoints & replay</summary><p>{data?.note}</p><p>Rewind by branching a saved checkpoint. This restores every department to the same saved state and leaves the original run intact. A new service day starts paused at 05:00.</p><div className="metro-command-layout"><label>Operator<input value={actor} onChange={e=>setActor(e.target.value)}/></label><label>Run / checkpoint name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Service date<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><label>Saved world<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Current run</option>{data?.runs.map(r=><option key={r.id} value={r.id}>{r.name} · {r.service_date}{r.id===data.active_id?' · active':''}</option>)}</select></label></div><div className="metro-action-row"><button disabled={busy||!actor||name.length<3} onClick={()=>void act('CHECKPOINT')}>Save checkpoint</button><button disabled={busy||!actor||!day||name.length<3} onClick={()=>void act('NEW_DAY')}>Start new service day</button><button disabled={busy||!actor||!source||name.length<3} onClick={()=>void act('BRANCH')}>Branch selected checkpoint</button><button disabled={busy||!actor||!source||name.length<3} onClick={()=>void act('REPLAY')}>Replay selected checkpoint</button></div>{error&&<p role="alert" className="metro-error">{error}</p>}</details>;
}
