"use client";
import {useState} from 'react';
import Link from 'next/link';
import {request} from '@/lib/api';
import {useResilientPolling} from '@/lib/useResilientPolling';
type Platform={id:string;line:string;towards:string;waiting:number;capacity:number;density_people_m2:number;oldest_wait_seconds:number;destinations:{station:string;passengers:number}[]};
type Station={id:string;name:string;waiting_passengers:number;walking:number;exiting:number;occupancy:number;occupancy_percent:number;entered:number;transfers:number;boarded:number;denied_boardings:number;platforms:Platform[];history:{seconds:number;waiting:number;occupancy:number;entered:number}[];weekday_profile:number[];environment:{power_failed?:boolean;access_closed?:boolean;backup?:boolean}};
type Vehicle={id:string;line:string;station:string;status:string;pilot:string|null;manual:boolean;crew_ready:boolean;reserve:boolean;passengers:number;capacity:number;hold_until:number};
type Decision={title?:string;stations?:string[];id:string;action:string;vehicle?:string;station:string;status:string;reason:string;created:number;expires:number;source:string;acknowledged_by?:string};
type Data={stations:Station[];vehicles:Vehicle[];decisions:Decision[];clock_seconds:number;running:boolean;quality:{source_conflicts:number;retimed:number;unassigned:number;fleet:number};conservation:{entered:number;exited:number;inside_stations:number;onboard:number;error:number};agent:{status:string;reason:string};config:{note:string}};
export default function MetroOperations({pilot=false,setup=false}:{pilot?:boolean;setup?:boolean}){
 const {data,error,setData,setError}=useResilientPolling<Data>({
  url: '/metro/operations',
  normalIntervalMs: 3000,
  timeoutMs: 30000,
  defaultErrorMessage: 'Metro state unavailable'
 });
 const [stationId,setStationId]=useState('AME'),[actor,setActor]=useState(''),[vehicle,setVehicle]=useState(''),[operation,setOperation]=useState('HOLD'),[value,setValue]=useState(120),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [profileText,setProfileText]=useState('');

 const submit=async(action:string,extra:Record<string,unknown>={})=>{setBusy(true);setError('');setNotice('');try{const next=await request<Data>('/metro/operations',{method:'POST',body:JSON.stringify({action,request_id:crypto.randomUUID(),actor,target:vehicle,station:stationId,operation,value,reason,...extra})},60000);setData(next);setNotice('Committed to the shared operating model.');}catch(e){setError(e instanceof Error?e.message:'Command not applied');}finally{setBusy(false);}};
 const station=data?.stations.find(s=>s.id===stationId)??data?.stations[0],train=data?.vehicles.find(v=>v.id===vehicle),pending=data?.decisions.filter(d=>['PENDING','APPROVED','ACKNOWLEDGED'].includes(d.status))??[];
 return <section className="metro-operations-v3" aria-label={pilot?'Metro Pilot operations':'Station passengers and operating decisions'}>
  <header><div><span className="metro-badge">SHARED OPERATING MODEL</span><h2>{pilot?'Pilot desk':'Passengers & service control'}</h2></div><Link href={pilot?'/metro-command':'/metro-pilot'}>{pilot?'Command desk →':'Open Pilot desk →'}</Link></header>
  {error&&<p role="alert" className="metro-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <div className="metro-ops-identity"><label>{pilot?'Pilot':'Operator'}<input value={actor} onChange={e=>setActor(e.target.value)} placeholder="Name for the command log"/></label><small>Local simulation identity · operational commands affect this shared run.</small></div>
  {!pilot&&<><label>Station<select aria-label="Passenger station" value={station?.id??''} onChange={e=>setStationId(e.target.value)}>{data?.stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
  {station&&<><div className="metro-ops-metrics">{[['On platforms',station.waiting_passengers],['Walking / concourse',station.walking],['Leaving station',station.exiting],['Total present',station.occupancy],['Occupancy',`${station.occupancy_percent}%`],['Transfers today',station.transfers]].map(([label,n])=><article key={label}><small>{label}</small><strong>{typeof n==='number'?n.toLocaleString():n}</strong></article>)}</div>
  <p>{station.environment.power_failed?'POWER INTERRUPTED · train movements held':station.environment.backup?'BACKUP POWER ACTIVE':station.environment.access_closed?'ACCESS CLOSED · passengers retained at access gates':'Station access open'} · generated passenger flows, not measured footfall.</p>
  <div className="metro-platform-grid">{station.platforms.map(p=><article key={p.id}><header><strong>{p.line} → {p.towards}</strong><span>{p.waiting.toLocaleString()} waiting</span></header><meter min={0} max={p.capacity} value={p.waiting}/><p>{p.density_people_m2} people/m² · oldest platform wait {Math.round(p.oldest_wait_seconds/60)} min · modeled platform limit {p.capacity}</p><details><summary>Passenger destinations</summary>{p.destinations.length?p.destinations.map(d=><p key={d.station}>{d.station}<strong>{d.passengers}</strong></p>):<p>No waiting passengers on this platform.</p>}</details></article>)}</div>
  <details><summary>Station history and calibration</summary><p>Entries {station.entered.toLocaleString()} · boardings {station.boarded.toLocaleString()} · left-behind boarding opportunities {station.denied_boardings.toLocaleString()}</p><svg viewBox="0 0 600 125" role="img" aria-label="Station occupancy over the last hour"><polyline fill="none" stroke="#78b3f2" strokeWidth="3" points={station.history.map((h,i)=>`${i*600/Math.max(1,station.history.length-1)},${115-h.occupancy/Math.max(1,...station.history.map(x=>x.occupancy))*100}`).join(' ')}/></svg><p>Weekday external entries: {Math.round(station.weekday_profile?.reduce((a,b)=>a+b,0)??0).toLocaleString()}/day. Transfers are counted separately. No minimum occupancy is forced.</p><p>{data?.config.note}</p></details></>}
  <section className="metro-agent"><h3>Metro decision agent · {data?.agent.status??'Connecting'}</h3><p>{data?.agent.reason}</p><strong>{pending.length} commands awaiting action</strong></section></>}
  <div className="metro-command-layout"><section><h3>{pilot?'Your train':'Issue an operating command'}</h3><label>Train<select aria-label="Operating train" value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Select vehicle</option>{data?.vehicles.map(v=><option key={v.id} value={v.id}>{v.id} · {v.line} · {v.status}{v.reserve?' · reserve':''}</option>)}</select></label>
  {train&&<p>{data?.stations.find(s=>s.id===train.station)?.name} · {train.passengers}/{train.capacity} passengers · {train.crew_ready?'Crew ready':'Crew acknowledgement required'} · {train.pilot??'Generated ATO crew'}</p>}
  {pilot?<div className="metro-action-row"><button disabled={!actor||!train||busy} onClick={()=>void submit('CLAIM')}>Claim train / manual departure</button><button disabled={!actor||!train||busy} onClick={()=>void submit('READY')}>Cab ready / authorize departure</button></div>:<><label>Command<select value={operation} onChange={e=>setOperation(e.target.value)}>{['HOLD','RELEASE','HEADWAY','EXTRA_SERVICE','SHORT_TURN'].map(o=><option key={o}>{o}</option>)}</select></label><label>{operation==='HEADWAY'?'Minimum separation (seconds)':'Hold duration (seconds)'}<input type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><p>Extra services require a reserve at the selected terminal. Short-turns are limited to modeled Ameerpet / Parade Ground facilities, with a feasible return slot.</p></>}
  <label>Reason / decision note<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Operational reason or rejection explanation"/></label>{!pilot&&<button disabled={!actor||!reason||busy} onClick={()=>void submit('PROPOSE',{platform:station?.platforms[0]?.id??''})}>Propose command</button>}</section>
  <section><h3>{pilot?'Approved instructions':'Review & execution'}</h3>{(pilot?pending.filter(d=>['APPROVED','ACKNOWLEDGED'].includes(d.status)&&(!vehicle||!d.vehicle||d.vehicle===vehicle)):pending).map(d=><article className="metro-decision" key={d.id}><header><strong>{d.title??`${d.action.replaceAll('_',' ')} · ${d.vehicle||'Network'}`}</strong><span>{d.status}</span></header>{d.stations&&<p><strong>Stations: {d.stations.join(' · ')}</strong></p>}<p>{d.reason}</p><small>{d.source} · expires in {Math.max(0,Math.ceil(d.expires-(data?.clock_seconds??0)))} simulation seconds</small><div className="metro-action-row">{!pilot&&d.status==='PENDING'&&<><button disabled={!actor||busy} onClick={()=>void submit('APPROVE',{target:d.id})}>Approve</button><button disabled={!actor||!reason||busy} onClick={()=>void submit('REJECT',{target:d.id})}>Reject with reason</button></>}{d.status==='APPROVED'&&<button disabled={!actor||busy} onClick={()=>void submit('ACKNOWLEDGE',{target:d.id})}>Acknowledge</button>}{d.status==='ACKNOWLEDGED'&&<button disabled={!actor||busy} onClick={()=>void submit('APPLY',{target:d.id})}>Apply approved command</button>}</div></article>)}{!pending.length&&<p>No pending commands. The agent evaluates platform crowding and waiting time every 30 simulation seconds.</p>}</section></div>
  {setup&&<details className="metro-setup"><summary>Central metro simulation inputs & calibration</summary><p>Applies to {station?.name}. Use a source-backed quarter-hour series when available; otherwise changes remain explicitly generated assumptions.</p><label>Daily external entries / fault duration in seconds<input type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><label>Optional 96 quarter-hour entry counts<textarea value={profileText} onChange={e=>setProfileText(e.target.value)} placeholder="Comma-separated counts from 00:00 to 23:45"/></label><div className="metro-action-row"><button disabled={!actor||!reason||busy} onClick={()=>void submit('PROFILE',{profile:profileText?profileText.split(',').map(Number):null})}>Save weekday demand</button><button disabled={!actor||!reason||busy} onClick={()=>void submit('FAULT',{fault:'ACCESS'})}>Close station access</button><button disabled={!actor||!reason||busy} onClick={()=>void submit('FAULT',{fault:'POWER'})}>Interrupt station supply</button><button disabled={!actor||!reason||busy} onClick={()=>void submit('CLEAR_FAULT')}>Restore station</button></div></details>}
  {data&&<details><summary>Conservation & timetable quality</summary><p>Entered {data.conservation.entered.toLocaleString()} = exited {data.conservation.exited.toLocaleString()} + inside stations {data.conservation.inside_stations.toLocaleString()} + onboard {data.conservation.onboard.toLocaleString()}. Difference: {data.conservation.error}.</p><p>{data.quality.fleet} generated physical train assignments · {data.quality.source_conflicts} source block conflicts · {data.quality.retimed} trips retimed for vehicle availability · {data.quality.unassigned} unassigned services. Source timetable is retained.</p><p>Statuses, commands, profiles and passengers are read from the shared database run. Train positions are simulated.</p></details>}
 </section>;
}
