import {test,expect} from "@playwright/test";
test.use({actionTimeout:15000});
test("GTFS trains move on geographic tracks from central playback controls",async({page})=>{
 await page.goto("/command");
 await expect(page.getByRole("heading",{name:"GOOGLE API BUDGET",exact:true})).toBeVisible();
 await expect(page.getByRole("row").filter({hasText:"ROAD TRAFFIC COVERAGE"})).toContainText("374,988",{timeout:30000});
 await expect(page.locator(".metro-train-marker").first()).toBeAttached({timeout:40000});
 await page.getByRole("button",{name:"Start metro playback",exact:true}).click();
 const movingId=await page.locator('.metro-train-marker[title*="IN_TRANSIT"]').first().getAttribute("data-train-id");
 const first=page.locator(`.metro-train-marker[data-train-id="${movingId}"]`);
 const positionOf=()=>first.evaluate(el=>[el.getAttribute("data-lon"),el.getAttribute("data-lat")].join(","));
 const before=await positionOf();
 await expect.poll(positionOf,{timeout:15000}).not.toBe(before);
 await page.getByRole("button",{name:"Pause metro playback",exact:true}).click();
 const a=await (await page.request.get("http://127.0.0.1:8001/metro/snapshot")).json();
 const b=await (await page.request.get("http://127.0.0.1:8001/metro/snapshot")).json();
 expect(a.state.running).toBe(false);expect(a.state.sim_seconds).toBe(b.state.sim_seconds);
 await page.getByRole("button",{name:"Start metro playback",exact:true}).click();
 await expect.poll(async()=>{const snapshot=await (await page.request.get("http://127.0.0.1:8001/metro/snapshot")).json();return snapshot.state.running;}).toBe(true);
 await page.goto("/metro-command");
 await expect(page.getByRole("heading",{name:"Metro Command",exact:true})).toBeVisible();
 await expect(page.getByRole("img",{name:"Hyderabad metro schematic network"})).toBeVisible();
 await expect(page.locator(".schematic-train").first()).toBeAttached({timeout:30000});
 await expect(page.locator(".maplibregl-canvas")).toHaveCount(0);
 const moving=page.locator('.schematic-train[data-status="IN_TRANSIT"]').first();
 const position=await moving.getAttribute("data-position");
 await expect.poll(()=>moving.getAttribute("data-position"),{timeout:5000}).not.toBe(position);
 await expect(page.locator(".metro-turnback")).toHaveCount(6);
 await page.getByRole("button",{name:"Schematic map",exact:true}).click();
 await expect(page.getByRole("button",{name:"Schematic map",exact:true})).toHaveAttribute("aria-pressed","true");
 await expect(page.locator('svg image')).toHaveCount(0);
 await expect(page.locator(".schematic-train").first()).toBeAttached();
 await page.getByRole("button",{name:"PDF map",exact:true}).click();
 await expect(page.locator('svg image')).toHaveCount(1);
 await expect(page.locator(".schematic-train").first()).toBeAttached();
 await page.screenshot({path:"test-results/metro-schematic.png",fullPage:true});
 await page.goto("/traffic");
 await page.getByText("Route calibration · optional Google reference",{exact:true}).click();
 await expect(page.getByRole("combobox",{name:"Calibration pair"})).toBeVisible();
 await expect(page.getByRole("button",{name:"Fetch one Google reference",exact:true})).toBeDisabled();
});
