"use client";
import {useEffect,useState} from 'react';
import * as ml from 'maplibre-gl';
import type {FeatureCollection,Point,Geometry,Feature} from 'geojson';
import {request} from '@/lib/api';
type Props={id:string;name:string;kind:string;parent_id:string;capacity_kva:number;zone_id:string};
const kinds=[['SUBSTATION','Substation','#94bdaa',11,0],['POWER_TRANSFORMER','Power transformer','#b3a4ce',9,12],['FEEDER','Feeder','#d6b57c',7,12],['DISTRIBUTION_TRANSFORMER','Distribution transformer','#8eb3d8',5,13]] as const;
export default function ElectricLayer({map}:{map:ml.Map|null}){
 const [data,setData]=useState<FeatureCollection<Geometry,Props>|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState(''),[visible,setVisible]=useState(true),[inspecting,setInspecting]=useState(false),[links,setLinks]=useState(true),[kind,setKind]=useState('SUBSTATION'),[search,setSearch]=useState('');
 useEffect(()=>{let alive=true;request<FeatureCollection<Geometry,Props>>('/command/scenario/electric-network',{},30000).then(d=>{if(alive)setData(d);}).catch(()=>{if(alive)setError('Electrical network unavailable. Reload after the database connects.');});return()=>{alive=false;};},[]);
 const points=data?.features.filter((f):f is Feature<Point,Props>=>f.geometry.type==='Point')??[];
 const asset=points.find(f=>f.properties.id===selected),parent=points.find(f=>f.properties.id===asset?.properties.parent_id),children=points.filter(f=>f.properties.parent_id===selected);
 useEffect(()=>{if(!map||!data)return;map.addSource('electric-network',{type:'geojson',data});map.addSource('electric-selected-links',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'electric-selected-links',type:'line',source:'electric-selected-links',paint:{'line-color':'#d0b885','line-width':2,'line-dasharray':[3,3],'line-opacity':.8}});
  const handlers:{id:string;handler:(e:ml.MapLayerMouseEvent)=>void}[]=[];
  for(const [type,,color,radius,minzoom] of kinds){
   const canvas=document.createElement('canvas');canvas.width=40;canvas.height=40;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#101e2c';ctx.strokeStyle=color;ctx.lineWidth=2;
   ctx.beginPath();if(type==='SUBSTATION')ctx.roundRect(3,3,34,34,4);else if(type==='FEEDER'){ctx.moveTo(20,2);ctx.lineTo(38,20);ctx.lineTo(20,38);ctx.lineTo(2,20);ctx.closePath();}else if(type==='POWER_TRANSFORMER'){for(let i=0;i<6;i++){const t=i*Math.PI/3;const x=20+18*Math.cos(t),y=20+18*Math.sin(t);if(!i)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.closePath();}else ctx.arc(20,20,16,0,Math.PI*2);ctx.fill();ctx.stroke();
   ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();if(type==='SUBSTATION'){ctx.moveTo(20,8);ctx.lineTo(11,31);ctx.moveTo(20,8);ctx.lineTo(29,31);ctx.moveTo(12,17);ctx.lineTo(28,17);ctx.moveTo(9,25);ctx.lineTo(31,25);}else if(type==='FEEDER'){ctx.moveTo(23,8);ctx.lineTo(15,21);ctx.lineTo(23,21);ctx.lineTo(17,32);}else{ctx.arc(16,20,7,0,Math.PI*2);ctx.moveTo(31,20);ctx.arc(24,20,7,0,Math.PI*2);}ctx.stroke();
   map.addImage(`electric-icon-${type}`,ctx.getImageData(0,0,40,40));const id=`electric-${type}`;map.addLayer({id,type:'symbol',source:'electric-network',filter:['all',['==',['geometry-type'],'Point'],['==',['get','kind'],type]],minzoom,layout:{'icon-image':`electric-icon-${type}`,'icon-size':radius/16+.2,'icon-allow-overlap':false}});
   const handler=(e:ml.MapLayerMouseEvent)=>{const id=e.features?.[0]?.properties?.id;if(id){setSelected(id);setInspecting(true);}};map.on('click',id,handler);handlers.push({id,handler});
  }
  return()=>{handlers.forEach(({id,handler})=>map.off('click',id,handler));try{for(const id of ['electric-selected-links',...kinds.map(k=>`electric-${k[0]}`)])if(map.getLayer(id))map.removeLayer(id);for(const id of ['electric-network','electric-selected-links'])if(map.getSource(id))map.removeSource(id);for(const [type] of kinds)if(map.hasImage(`electric-icon-${type}`))map.removeImage(`electric-icon-${type}`);}catch{}};
 },[map,data]);
 useEffect(()=>{if(!map?.getSource('electric-network'))return;for(const [type] of kinds)map.setLayoutProperty(`electric-${type}`,'visibility',visible?'visible':'none');
  const ancestorIds=new Set<string>();let node=asset;while(node&&!ancestorIds.has(node.properties.id)){ancestorIds.add(node.properties.id);node=points.find(p=>p.properties.id===node?.properties.parent_id);}
  const features=visible&&links&&selected?data!.features.filter(f=>f.geometry.type==='LineString'&&(f.properties.parent_id===selected||ancestorIds.has(f.properties.id))):[];
  (map.getSource('electric-selected-links') as ml.GeoJSONSource).setData({type:'FeatureCollection',features});
 },[map,data,visible,links,selected]);
 const choose=(id:string)=>{setSelected(id);setVisible(true);setInspecting(true);const f=points.find(p=>p.properties.id===id);if(f)map?.flyTo({center:f.geometry.coordinates as [number,number],zoom:f.properties.kind==='DISTRIBUTION_TRANSFORMER'?16:14,duration:650});};
 const options=points.filter(p=>p.properties.kind===kind&&`${p.properties.name} ${p.properties.id}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="electric-network-control" aria-label="Electrical map layer"><button aria-pressed={visible} onClick={()=>setVisible(!visible)}>ϟ Electric grid {visible?'on':'off'}</button><button onClick={()=>setInspecting(!inspecting)}>Find equipment</button><span>Substations → feeders → transformers · zoom for local assets</span>{error&&<p role="alert">{error}</p>}
  {inspecting&&<section className="electric-inspector" aria-label="Electrical equipment inspector"><header><div><small>ELECTRICAL NETWORK</small><h3>Equipment & supply</h3></div><button aria-label="Close electrical inspector" onClick={()=>setInspecting(false)}>✕</button></header><div className="electric-inspector-body"><div className="electric-find"><label>Equipment type<select aria-label="Electrical equipment type" value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Search by name or ID<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search equipment"/></label><label>Select equipment<select aria-label="Electrical asset" value={options.some(p=>p.properties.id===selected)?selected:''} onChange={e=>choose(e.target.value)}><option value="">{options.length} matching assets</option>{options.map(p=><option key={p.properties.id} value={p.properties.id}>{p.properties.name}</option>)}</select></label></div>
   {asset?<><div className="electric-asset-title"><h3>{asset.properties.name}</h3><button onClick={()=>choose(asset.properties.id)}>Locate ⌖</button></div><p>{kinds.find(k=>k[0]===asset.properties.kind)?.[1]} · {asset.properties.capacity_kva??'—'} kVA capacity</p><button aria-pressed={links} onClick={()=>setLinks(!links)}>Supply links {links?'shown':'hidden'}</button><p>Dashed links show the selected supply relationship, not surveyed cable routes.</p><section className="electric-supply-tree" aria-label="Supply connections">{parent&&<button onClick={()=>choose(parent.properties.id)}>↑ {parent.properties.name}</button>}<strong>{asset.properties.name}</strong><span>{children.length} connected downstream assets</span><div>{children.map(c=><button key={c.properties.id} onClick={()=>choose(c.properties.id)}>{c.properties.name}<small>{kinds.find(k=>k[0]===c.properties.kind)?.[1]} · {c.properties.capacity_kva} kVA</small></button>)}</div></section></>:<p>Select an asset on the map or find one above to inspect its connected equipment.</p>}
   <p className="electric-provenance">Generated equipment positions and parent relationships, stored in the database. Distribution transformers appear from zoom 13.</p></div></section>}
 </section>;
}
