"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {request} from '@/lib/api';
import ApiBudget from './ApiBudget';
import WeatherOverview from './WeatherOverview';
import './main-command.css';
import './operations-console.css';
type LatLng={lat:number;lng:number};
type MapObject={fitBounds:(b:unknown)=>void};
type Overlay={setMap:(m:MapObject|null)=>void};
type Maps={Map:new(e:HTMLElement,o:object)=>MapObject;Polyline:new(o:object)=>Overlay;Marker:new(o:object)=>Overlay;LatLngBounds:new()=>{extend:(p:LatLng)=>void};TrafficLayer:new()=>Overlay};
type Result={mode:string;reason?:string;coordinates?:number[][];distanceM?:number;normalDurationSec?:number;trafficDurationSec?:number;trafficRatio?:number;conflicts?:string[];operationallyUsable?:boolean;data?:{places?:{id:string;displayName?:{text:string};location?:{latitude:number;longitude:number}}[];results?:{elevation:number}[]}};
export default function GoogleOperations(){
 const container=useRef<HTMLDivElement>(null),maps=useRef<Maps|null>(null),map=useRef<MapObject|null>(null),overlays=useRef<Overlay[]>([]);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 const [clock,setClock]=useState('');
 useEffect(()=>{const tick=()=>setClock(new Date().toLocaleTimeString('en-IN',{hour12:false,timeZone:'Asia/Kolkata'}));tick();const t=setInterval(tick,1000);return()=>clearInterval(t);},[]);
 const [origin,setOrigin]=useState<LatLng>({lat:17.4435,lng:78.3772}),[destination,setDestination]=useState<LatLng>({lat:17.4353,lng:78.3845});
 useEffect(()=>()=>{overlays.current.forEach(o=>o.setMap(null));},[]);
 const load=async()=>{setBusy(true);setError('');try{
 const key=process.env.NEXT_PUBLIC_GOOGLE_MAPS_BROWSER_KEY||process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
 if(!key)throw Error('Google browser key is not configured');
 const w=window as unknown as {google?:{maps:Maps}};
 if(!w.google){await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}`;s.async=true;s.onload=()=>resolve();s.onerror=()=>reject(Error('Google map failed to load'));document.head.appendChild(s);});}
 maps.current=w.google!.maps;map.current=new maps.current.Map(container.current!,{center:origin,zoom:13,mapTypeControl:false,streetViewControl:false,colorScheme:'LIGHT'});
 const traffic=new maps.current.TrafficLayer();traffic.setMap(map.current);overlays.current.push(traffic);setReady(true);
 }catch(e){setError(e instanceof Error?e.message:'Map unavailable');}finally{setBusy(false);}};
 const run=async(kind:'route'|'hospitals'|'snap'|'elevation')=>{setBusy(true);setError('');try{
 const path={route:'/api/routes/compute',hospitals:'/api/places/nearby',snap:'/api/roads/nearest',elevation:'/api/elevation/lookup'}[kind];
 const body=kind==='route'?{origin,destination}:kind==='hospitals'?{...origin,category:'hospital',radius_m:3000}:{points:[origin]};
 const r=await request<Result>(path,{method:'POST',body:JSON.stringify(body)},30000);setResult(r);
 if(r.mode==='UNAVAILABLE'){setError(r.reason??'Provider unavailable');return;}
 if(kind==='route'&&r.coordinates&&maps.current&&map.current){const coords=r.coordinates.map(p=>({lat:p[1],lng:p[0]}));const bounds=new maps.current.LatLngBounds();coords.forEach(p=>bounds.extend(p));overlays.current.slice(1).forEach(o=>o.setMap(null));overlays.current=overlays.current.slice(0,1);overlays.current.push(new maps.current.Polyline({map:map.current,path:coords,strokeColor:r.operationallyUsable?'#49d9ce':'#ef6374',strokeWeight:5}));map.current.fitBounds(bounds);}
 if(kind==='hospitals'&&maps.current&&map.current)for(const p of r.data?.places??[])if(p.location)overlays.current.push(new maps.current.Marker({map:map.current,position:{lat:p.location.latitude,lng:p.location.longitude},title:p.displayName?.text??p.id}));
 }catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}};
 const hasRoute=result?.distanceM!=null;
 return <main className="ops-console">
 <header className="ops-header"><Link href="/command" className="ops-brand"><svg width="38" height="44" viewBox="0 0 38 44" aria-hidden="true"><path d="M19 2 35 8 32 29 19 42 6 29 3 8Z" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="m21 9-11 16h9l-2 11 12-18h-9Z" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg><span>AEGISGRID<small>URBAN INFRASTRUCTURE COMMAND</small></span></Link><div className="ops-jurisdiction"><span>TELANGANA / HYDERABAD</span><h1>City Operations Centre</h1></div><div className="ops-header-status"><span className={error?'ops-status warning':'ops-status'}><i/>{error?'SERVICE ATTENTION':busy?'REQUEST IN PROGRESS':ready?'MAP CONNECTED':'STANDBY'}</span><strong>{clock||'—'}<small>INDIA STANDARD TIME</small></strong></div></header>
 <nav className="ops-nav" aria-label="Command departments"><Link href="/command">Command overview</Link><Link href="/google-operations" aria-current="page">Live intelligence</Link><Link href="/traffic">Traffic operations</Link><Link href="/ambulance">Emergency response</Link><Link href="/electric-command">Power network</Link><Link href="/metro-command">Metro control</Link><span>OPERATOR WORKSPACE</span></nav>
 <div className="ops-page-heading"><div><span className="ops-eyebrow">LIVE INTELLIGENCE / NETWORK OPERATIONS</span><h2>Hyderabad operational picture</h2><p>Traffic conditions, emergency access and environmental intelligence.</p></div><span className="ops-source">GOOGLE MAPS PLATFORM</span></div>
 <section className="ops-metrics" aria-label="Route assessment"><article><span>ROUTE DISTANCE</span><strong>{hasRoute?(result!.distanceM!/1000).toFixed(2):'—'}<small>{hasRoute?'km':''}</small></strong><p>{hasRoute?'Computed road distance':'Awaiting route assessment'}</p></article><article><span>TRAFFIC-AWARE ETA</span><strong>{hasRoute?((result!.trafficDurationSec??0)/60).toFixed(1):'—'}<small>{hasRoute?'min':''}</small></strong><p>{hasRoute?'Google traffic estimate':'No active route'}</p></article><article><span>TRAVEL TIME RATIO</span><strong>{hasRoute?result!.trafficRatio?.toFixed(2):'—'}<small>{hasRoute?'×':''}</small></strong><p>{hasRoute?'Relative to baseline travel time':'Requires a route assessment'}</p></article><article className={result?.conflicts?.length?'ops-metric-alert':''}><span>LOCAL CONFLICT CHECK</span><strong className="ops-metric-text">{hasRoute?(result!.conflicts?.length?'REVIEW REQUIRED':'NO CONFLICT FOUND'):'NOT ASSESSED'}</strong><p>{hasRoute?'Operator approval still required':'Incidents and flood areas'}</p></article></section>
 <div className="ops-workspace"><aside className="ops-planning"><section className="ops-panel"><header><span className="ops-section-number">01</span><h3>Route assessment</h3><span className="ops-tag">PLANNING</span></header><div className="ops-form"><p>Set the response corridor endpoints.</p>{[['Origin',origin,setOrigin],['Destination',destination,setDestination]].map(([name,p,set],i)=>{const point=p as LatLng;const setter=set as typeof setOrigin;return <fieldset key={String(name)}><legend><i className={i?'destination':'origin'}/>{String(name)}</legend><div className="ops-coordinate-pair">{(['lat','lng'] as const).map(k=><label key={k}>{k==='lat'?'Latitude':'Longitude'}<input type="number" step="0.0001" value={point[k]} onChange={e=>setter({...point,[k]:Number(e.target.value)})}/></label>)}</div></fieldset>;})}<button className="ops-primary" disabled={!ready||busy} onClick={()=>run('route')}>{busy?'Processing request…':'Assess route'}<span>→</span></button><p className="ops-disclaimer">Planning coordinates · not live ambulance GPS.</p></div></section><section className="ops-panel"><header><span className="ops-section-number">02</span><h3>Location intelligence</h3></header><div className="ops-intel-actions"><button disabled={!ready||busy} onClick={()=>run('hospitals')}><span className="ops-action-symbol">✚</span><span>Emergency facilities<small>Locate nearby hospitals</small></span><b>↗</b></button><button disabled={!ready||busy} onClick={()=>run('snap')}><span className="ops-action-symbol">⌁</span><span>Road correspondence<small>Check nearest road</small></span><b>↗</b></button><button disabled={!ready||busy} onClick={()=>run('elevation')}><span className="ops-action-symbol">△</span><span>Terrain context<small>Read elevation at origin</small></span><b>↗</b></button></div></section><div className="ops-workflow-note"><span>OPERATIONAL WORKFLOW</span><p>Route assessment supports decisions. Corridor requests and approvals remain in the emergency and traffic portals.</p><Link href="/ambulance">Open emergency response →</Link></div></aside>
 <section className="ops-map-panel"><header><div><span className="ops-section-number">03</span><h3>Live network map</h3></div><span className="ops-map-state"><i/>{ready?'GOOGLE TRAFFIC LAYER':'MAP NOT LOADED'}</span></header><div className="ops-map-wrap"><div ref={container} className="ops-map" aria-label="Google operations map"/>{!ready&&<div className="ops-map-start"><div className="ops-map-grid"/><div className="ops-map-start-content"><span className="ops-eyebrow">HYDERABAD / REGIONAL COVERAGE</span><h3>Connect the operational map</h3><p>Open live traffic, road context and emergency facility locations.</p><button className="ops-primary" disabled={busy} onClick={load}>{busy?'Connecting…':'Connect live map'}<span>↗</span></button></div></div>}</div><footer><span><i className="ops-line teal"/>Calculated route</span><span><i className="ops-line red"/>Local conflict</span><span>Traffic overlay supplied by Google</span></footer>{error&&<div className="ops-alert" role="alert"><strong>Service attention</strong><p>{error.replaceAll('_',' ')}</p></div>}<div className="ops-assessment"><div><span className="ops-eyebrow">LATEST ASSESSMENT</span><h3>{result?(result.mode==='UNAVAILABLE'?'Provider unavailable':hasRoute?'Route review available':'Location query complete'):'Ready for operator input'}</h3></div><span className="ops-tag">{result?`${result.mode} · GOOGLE`:'AWAITING REQUEST'}</span>{result?.conflicts&&<p>{result.conflicts.length?`${result.conflicts.length} local conflicts detected. This route must not be used for corridor activation.`:'No conflict detected by the local proximity check. This is not confirmation that every road is accessible.'}</p>}{result?.data?.places?.map(p=><div className="ops-facility" key={p.id}><span>✚</span><strong>{p.displayName?.text??'Hospital'}</strong><small>{p.id}</small></div>)}{result?.data?.results?.map((r,i)=><p key={i}>Terrain elevation <strong>{r.elevation.toFixed(1)} m</strong> · elevation alone does not establish flood risk.</p>)}{!result&&<p>Connect the map, then assess a route or query a location. Results and source labels appear here.</p>}</div></section>
 <aside className="ops-context"><WeatherOverview/><details className="ops-budget"><summary><span>API resource usage</span><span>⌄</span></summary><ApiBudget/></details><section className="ops-provenance"><span className="ops-eyebrow">DATA INTEGRITY</span><div><i className="live"/><p><strong>Live external intelligence</strong><small>Weather and geographic services</small></p></div><div><i className="derived"/><p><strong>Derived assessments</strong><small>Traffic ETA and conflict checks</small></p></div><div><i className="sim"/><p><strong>Municipal simulation</strong><small>Infrastructure telemetry in department portals</small></p></div></section></aside></div>
 <footer className="ops-footer"><span>AEGISGRID · HYDERABAD DIGITAL TWIN</span><span>Decision support workspace · operator approval required for corridor actions</span></footer></main>;
}
