"use client";
import {useEffect,useState,useRef} from "react";
import {request} from "@/lib/api";
export type ScenarioSnapshot={ready:boolean;asset_counts:Record<string,number>;electric:{load_kva:number;load_percent:number;overloaded_transformers:number;affected_transformers:number};passengers:{waiting:number;arrived:number;boarded:number;onboard:number};version:number;running:boolean;speed:number;seconds:number;clock:string;note:string;scenarios:{id:string;kind:string;polygon:number[][];station_ids?:string[];station_targets?:{id:string;name:string;position:number[]}[];status:string;rain_mm_hour:number;water_mm:number;traffic_factor:number;electric_factor:number;metro_factor:number;blocked:boolean;affected:Record<string,number>;electrical_impact?:{load_kva:number;baseline_kva:number;delta_kva:number;transformers:number}}[];events:{id:string;kind:string;sim_seconds:number;parent_event_id:string|null}[];recommendations:{id:string;status:string;action:string;reason:string}[]};
export function useScenario(){
 const [data,setData]=useState<ScenarioSnapshot|null>(null),[error,setError]=useState("");
 useEffect(()=>{let alive=true;let timer:ReturnType<typeof setTimeout>;const refresh=async()=>{try{const next=await request<ScenarioSnapshot>("/command/scenario",{},15000);if(alive){setData(next);setError("");}}catch{if(alive)setError("Shared simulation is loading or disconnected. Controls remain unavailable until the database responds.");}if(alive)timer=setTimeout(refresh,3000);};void refresh();return()=>{alive=false;clearTimeout(timer);};},[]);
 return {data,error,setData,setError};
}
export default function ScenarioControls({polygon,drawing,onDraw,onClear,readOnly=false,dock=false}:{polygon:number[][];drawing:boolean;onDraw:()=>void;onClear:()=>void;readOnly?:boolean;dock?:boolean}){
 const {data,error,setData}=useScenario();const [busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[notice,setNotice]=useState(''),[kind,setKind]=useState("RAIN"),[intensity,setIntensity]=useState(60),[duration,setDuration]=useState(60),[multiplier,setMultiplier]=useState(1.5),[targetTime,setTargetTime]=useState("12:00");
 const [stations,setStations]=useState<{id:string;name:string}[]>([]),[stationIds,setStationIds]=useState<string[]>([]),[stationError,setStationError]=useState('');
 useEffect(()=>{if(kind!=='METRO')return;let alive=true;request<{stations:{id:string;name:string}[]}>('/command/scenario/metro-targets',{},15000).then(d=>{if(alive){setStations(d.stations);setStationError('');}}).catch(()=>{if(alive)setStationError('Station list unavailable. Reopen Metro demand to retry.');});return()=>{alive=false;};},[kind]);
 const act=async(action:string,extra:Record<string,unknown>={})=>{setBusy(true);setActionError('');try{const next=await request<ScenarioSnapshot>("/command/scenario",{method:"POST",body:JSON.stringify({action,request_id:crypto.randomUUID(),polygon,station_ids:stationIds,intensity,duration_minutes:duration,multiplier,...extra})},30000);setData(next);if(['RAIN','FLOOD','ELECTRIC','TRAFFIC','SIGNAL','METRO'].includes(action)){onClear();if(dock)setOpen(false);}setNotice(['RAIN','FLOOD','ELECTRIC','TRAFFIC','SIGNAL','METRO'].includes(action)?`Input saved. ${next.running?'Effects are advancing with the clock.':'Press Run to advance accumulation and movement.'}`:'Change saved to the shared run.');}catch(e){setActionError(e instanceof Error?e.message:"Change could not be confirmed.");}finally{setBusy(false);}};
 const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 const disabled=busy||!data||!!error;
 const desk=<section className="city-simulation" aria-label="Shared scenario controls">
 <div className="scenario-title"><div><span className="eyebrow">CONTROL DESK</span><h2>{readOnly?'Shared scenario':'Scenario control'}</h2></div><span className={`run-status ${data?.running?'running':''}`}>{!data?'Connecting':data.running?'Running':'Paused'}</span></div>
 <div className="scenario-clock"><strong>{data?.clock??'—'}</strong><span>IST · simulation clock</span></div>
 {!readOnly&&<><div className="scenario-playback"><button className="primary" disabled={disabled} onClick={()=>void act(data?.running?'PAUSE':'PLAY')}>{data?.running?'Ⅱ Pause':'▶ Run'}</button><label>Speed<select aria-label="Shared simulation speed" disabled={disabled} value={data?.speed??1} onChange={e=>void act('SPEED',{speed:Number(e.target.value)})}>{[1,5,10,30,60].map(v=><option key={v} value={v}>{v}×</option>)}</select></label></div>
 <div className="scenario-form"><label>Event<select aria-label="Scenario event" value={kind} onChange={e=>setKind(e.target.value)}>{[['RAIN','Rainfall'],['FLOOD','Flooding'],['ELECTRIC','Electrical demand'],['TRAFFIC','Traffic disruption'],['SIGNAL','Signal failure'],['METRO','Metro demand']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <div className="scenario-fields">{['RAIN','FLOOD'].includes(kind)?<label>{kind==='RAIN'?'Rainfall · mm/h':'Water depth · mm'}<input aria-label="Rainfall intensity" type="number" min={0} max={300} value={intensity} onChange={e=>setIntensity(Number(e.target.value))}/></label>:kind!=='SIGNAL'?<label>Demand multiplier<input aria-label="Demand multiplier" type="number" min={.1} max={4} step={.1} value={multiplier} onChange={e=>setMultiplier(Number(e.target.value))}/></label>:null}<label>Duration · minutes<input aria-label="Scenario duration" type="number" min={1} max={1440} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label></div>
 {kind==='METRO'?<div className="scenario-station-selection"><label>Metro stations<select aria-label="Metro station selection" value="" onChange={e=>{if(e.target.value)setStationIds(old=>Array.from(new Set([...old,e.target.value])));}}><option value="">Select a station…</option>{stations.filter(s=>!stationIds.includes(s.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="scenario-station-chips">{stationIds.map(id=><button key={id} aria-label={`Remove station ${stations.find(s=>s.id===id)?.name??id}`} onClick={()=>setStationIds(old=>old.filter(i=>i!==id))}>{stations.find(s=>s.id===id)?.name??id} ×</button>)}</div><button disabled={!stations.length} onClick={()=>setStationIds(stations.map(s=>s.id))}>Select all stations</button>{stationIds.length>0&&<button onClick={()=>setStationIds([])}>Clear stations</button>}<p>{stationIds.length} stations selected. Arrival rates change with the shared clock; queues, boarding and capacity use the existing timetable.</p>{stationError&&<p role="alert">{stationError}</p>}</div>:<div className="scenario-selection"><span>{drawing?`Drawing · ${polygon.length} corners`:polygon.length>=3?'Area selected':'Select an area on the map'}</span><div><button disabled={disabled||(drawing&&polygon.length<3)} onClick={()=>{onDraw();if(dock)setOpen(false);}}>{drawing?'Finish area':polygon.length?'Adjust area':'Draw area'}</button>{polygon.length>0&&<button disabled={busy} onClick={onClear}>Clear drawing</button>}</div></div>}
 <button className="primary scenario-inject" disabled={disabled||(kind==='METRO'?stationIds.length===0||!!stationError:polygon.length<3||drawing)} onClick={()=>void act(kind)}>{busy?'Saving…':kind==='METRO'?'Apply demand to selected stations':'Apply event to area'}</button>
 </div></>}
 {(error||actionError)&&<p role="alert" className="main-warning">{actionError||error}</p>}{notice&&<p className="scenario-notice" role="status">{notice}</p>}
 <p className="scenario-caption">Simulation inputs change the shared model. Google weather remains a separate observation.</p>
 <details className="scenario-details"><summary>Clock settings</summary>{!readOnly&&<><label>Advance to time · IST<input aria-label="Simulation time" type="time" value={targetTime} onChange={e=>setTargetTime(e.target.value)}/></label><button disabled={disabled||!targetTime} onClick={()=>{const [h,m]=targetTime.split(':').map(Number);void act('SET_TIME',{seconds:h*3600+m*60});}}>Advance and pause</button></>}<p>Time advances through the model; rewinding this run is disabled.</p></details>
 <details className="scenario-details" open={!!data?.recommendations.some(r=>r.status==='PENDING')}><summary>Recommendations · {data?.recommendations.filter(r=>r.status==='PENDING').length??0} pending</summary>{!data?.recommendations.length&&<p>Drainage is recommended after water accumulation reaches 30 mm.</p>}{data?.recommendations.map(r=><article key={r.id}><strong>{r.action}</strong><p>{r.reason}</p><span>{r.status}</span>{!readOnly&&r.status==='PENDING'&&<div className="scenario-actions"><button disabled={disabled} onClick={()=>void act('APPROVE',{target_id:r.id})}>Approve pumps</button><button disabled={disabled} onClick={()=>void act('REJECT',{target_id:r.id})}>Reject</button></div>}</article>)}</details>
 <details className="scenario-details"><summary>Manage areas · {data?.scenarios.length??0}</summary>{data?.scenarios.map((z,i)=><article key={z.id}><strong>Area {i+1} · {z.kind} · {z.status}</strong><p>{z.kind==='METRO'?`${z.station_targets?.map(s=>s.name).join(', ')??'Legacy area'} · arrivals ×${z.metro_factor.toFixed(2)}`:`${z.rain_mm_hour.toFixed(0)} mm/h rain · ${z.water_mm.toFixed(1)} mm water`}</p>{!readOnly&&z.status==='ACTIVE'&&<button disabled={disabled} onClick={()=>void act('END',{target_id:z.id})}>Stop input · allow drainage</button>}{!readOnly&&<button disabled={disabled} onClick={()=>void act('REMOVE',{target_id:z.id})}>Remove input & current effects</button>}</article>)}</details>
 <details className="scenario-details"><summary>Event history</summary>{data?.events.slice(-15).reverse().map(e=><p key={e.id}>{Math.floor(e.sim_seconds)}s · {e.kind.replaceAll('_',' ')}</p>)}</details>
 </section>;
 if(!dock)return desk;
 return <><section className="atlas-dock" aria-label="Event simulation controls"><div className="atlas-dock-heading"><h2>EVENT SIMULATION</h2><span>Choose an event · set its targets · observe the response</span><button className="atlas-dock-review" onClick={()=>setOpen(true)}>Actions & history {data?.recommendations.filter(r=>r.status==='PENDING').length?`· ${data.recommendations.filter(r=>r.status==='PENDING').length} pending`:'↗'}</button></div><div className="atlas-dock-row">{!readOnly&&<div className="atlas-event-buttons">{[['RAIN','☂','Rainfall'],['ELECTRIC','ϟ','Power demand'],['TRAFFIC','⇄','Traffic disruption'],['SIGNAL','🚦','Signal failure'],['FLOOD','≋','Flood area'],['METRO','▣','Metro demand']].map(([value,icon,label])=><button key={value} className={kind===value&&open?'selected':''} onClick={()=>{setKind(value);setOpen(true);}}><span aria-hidden="true">{icon}</span>{label}</button>)}</div>}{readOnly&&<p>Scenario inputs are managed in the <a href="/command">main command center ↗</a>.</p>}<div className="atlas-dock-playback"><span className={data?.running?'running':''}>{data?.running?'RUNNING':'PAUSED'}</span>{!readOnly&&<><button className="primary" disabled={disabled} onClick={()=>void act(data?.running?'PAUSE':'PLAY')}>{data?.running?'Ⅱ Pause':'▶ Run'}</button><select aria-label="Simulation playback speed" disabled={disabled} value={data?.speed??1} onChange={e=>void act('SPEED',{speed:Number(e.target.value)})}>{[1,5,10,30,60].map(v=><option key={v} value={v}>{v}×</option>)}</select></>}</div></div>{(actionError||error)&&<p className="main-warning" role="alert">{actionError||error}</p>}{notice&&!open&&<p className="atlas-dock-notice" role="status">{notice}</p>}</section><dialog ref={dialog} className="atlas-dialog atlas-config-dialog" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===dialog.current)setOpen(false);}}><div className="atlas-dialog-header"><h2>Scenario configuration</h2><button aria-label="Close scenario configuration" onClick={()=>setOpen(false)}>✕</button></div>{desk}</dialog></>;
}
