"use client";
import { useEffect,useState } from "react";
import { request } from "@/lib/api";
type Pair={id:string;name:string};
type Snapshot={pair_id:string;aegis:{distance_m:number;eta_seconds:number;turn_count:number;road_class_mix:Record<string,number>};google:{status:string;reason?:string;distance_m?:number;duration_sec?:number;observed_at?:string};comparison:{status:string;diagnostics:string[]}|null};
export default function RouteCalibration(){
 const [pairs,setPairs]=useState<Pair[]>([]),[selected,setSelected]=useState(""),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[approved,setApproved]=useState(false),[token,setToken]=useState(""),[operator,setOperator]=useState(""),[evidence,setEvidence]=useState(""),[config,setConfig]=useState(""),[version,setVersion]=useState(0);
 const refresh=async()=>{const [p,s,c]=await Promise.all([request<{pairs:Pair[]}>("/calibration/pairs"),request<{snapshots:Snapshot[]}>("/calibration/snapshots"),request<{parameters:object;version:number}>("/calibration/config")]);setPairs(p.pairs);setSnapshots(s.snapshots);setConfig(JSON.stringify(c.parameters,null,2));setVersion(c.version);};
 useEffect(()=>{void Promise.resolve().then(refresh).catch(()=>setError("Calibration data unavailable"));},[]);
 const act=async(path:string,body:object)=>{setBusy(true);setError("");try{await request(path,{method:"POST",headers:{"X-Aegis-Operator-Token":token},body:JSON.stringify(body)});setApproved(false);await refresh();}catch(e){setError(e instanceof Error?e.message:"Action failed");}finally{setBusy(false);}};
 const row=snapshots.find(s=>s.pair_id===selected);
 return <details className="dispatch-panel" style={{padding:20,margin:20}}><summary>Route calibration · optional Google reference</summary><p>Manual comparison only. Aegis routes remain OSM + NetworkX. No Google geometry is displayed or retained.</p><select aria-label="Calibration pair" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select area pair</option>{pairs.map(p=><option key={p.id} value={p.id}>{p.id} · {p.name}</option>)}</select><label>Operator token <input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I approve this selected fetch or configuration change</label><button disabled={busy||!selected||!approved||!token} onClick={()=>void act(`/calibration/google/fetch/${selected}`,{pair_ids:[selected],approved})}>Fetch one Google reference</button><button disabled={busy} onClick={()=>void refresh().catch(()=>setError("Refresh failed"))}>Read saved session results · no Google call</button>{error&&<p role="alert">{error}</p>}
 {row&&<div><h3>AEGIS ROUTE</h3><p>{row.aegis.distance_m} m · {(row.aegis.eta_seconds/60).toFixed(1)} min modeled · {row.aegis.turn_count} turns</p><p>{Object.entries(row.aegis.road_class_mix).map(([k,v])=>`${k}: ${v}%`).join(" · ")}</p><h3>GOOGLE REFERENCE</h3><p>{row.google.status==="AVAILABLE"?`${row.google.distance_m} m · ${((row.google.duration_sec??0)/60).toFixed(1)} min · ${row.google.observed_at}`:row.google.reason}</p><strong>{row.comparison?.status}</strong>{row.comparison?.diagnostics.map(d=><p key={d}>{d}</p>)}</div>}
 <details><summary>Bounded operator calibration · revision {version}</summary><p>Initial values are unvalidated assumptions. Applying changes records evidence and before/after values. Revert restores the preceding configuration.</p><label>Operator <input value={operator} onChange={e=>setOperator(e.target.value)}/></label><label>Evidence <input value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><textarea aria-label="Routing parameters" rows={14} style={{width:"100%",fontFamily:"monospace"}} value={config} onChange={e=>setConfig(e.target.value)}/><button disabled={busy||!approved||!token} onClick={()=>{try{void act("/calibration/apply",{approved,operator,evidence,version,parameters:JSON.parse(config)});}catch{setError("Invalid parameter JSON");}}}>Apply approved values</button><button disabled={busy||!approved||!token} onClick={()=>void act("/calibration/revert",{approved,operator,evidence,version})}>Revert previous change</button></details></details>;
}
