import type { Coordinate, MapMode, RouteResult } from "@/types/aegis";
type Props = { start: Coordinate | null; end: Coordinate | null; mode: MapMode; route: RouteResult | null; loading: boolean; locked: boolean; error: string; onMode: (mode: MapMode) => void; onCalculate: () => void; onReset: () => void };
const position = (point: Coordinate | null) => point ? `${point.lat.toFixed(5)}, ${point.lon.toFixed(5)}` : "Select on map";
export default function RoutePanel(p: Props) {
  return <section className="panel route-panel compact-route"><div className="section-heading"><h2>Route planning</h2><span className="small-tag">NETWORKX / OSM</span><span className="route-state">{p.loading ? "COMPUTING" : p.route ? "Route calculated" : "No active route"}</span></div>
    <div className="route-inputs">{([['start','A','START',p.start],['destination','B','DESTINATION',p.end]] as const).map(([mode,letter,label,point])=><button key={mode} className={`point-row ${p.mode === mode ? "selected" : ""}`} disabled={p.locked} onClick={()=>p.onMode(mode)}><span className={`point-letter ${mode}`}>{letter}</span><span><strong>{label}</strong><small>{position(point)}</small></span><span className="point-edit">↗</span></button>)}<button className="primary" disabled={!p.start || !p.end || p.loading || p.locked} onClick={p.onCalculate}>{p.loading ? "Calculating…" : "Calculate route →"}</button><button className="secondary" disabled={p.locked} onClick={p.onReset}>Reset</button></div>
    <div className="route-telemetry"><div><span>DISTANCE</span><strong>{p.route ? `${p.route.distance_km.toFixed(2)} km` : "—"}</strong></div><div><span>FREE-FLOW ETA</span><strong>{p.route ? `${p.route.eta_minutes.toFixed(1)} min` : "—"}</strong></div><div><span>ROUTE EDGES</span><strong>{p.route?.route_edges.length ?? "—"}</strong></div><div><span>BACKEND TIME</span><strong>{p.route ? `${p.route.total_ms.toFixed(0)} ms` : "—"}</strong></div><div><span>GRAPH CACHE</span><strong>{p.route ? p.route.cache_hit ? "HIT" : "MISS" : "—"}</strong></div></div>
    <div aria-live="polite">{p.loading && <p className="loading-note">Loading road graph. Cold requests can take several minutes.</p>}{p.error && <p className="error-note" role="alert">{p.error}</p>}</div>
    {p.route?.snapping && <div className="snap-summary" aria-label="Road snapping details">Road offsets A {p.route.snapping.start.distance_m.toFixed(1)} m / B {p.route.snapping.end.distance_m.toFixed(1)} m · dashed click offsets are not routed.</div>}
    {p.route && <details className="route-diagnostics"><summary>Backend diagnostics &amp; road names</summary><dl className="detail-list">{[["Routing engine",p.route.route.properties.engine],["Road data",p.route.route.properties.source],["Graph load",`${p.route.graph_load_ms.toFixed(0)} ms`],["Endpoint snapping",`${p.route.endpoint_snap_ms.toFixed(0)} ms`],["Path computation",`${p.route.route_compute_ms.toFixed(0)} ms`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>{Array.from(new Set(p.route.route_edges.map(e=>e.road_name||"Unnamed road"))).join(" → ")}</p></details>}
  </section>;
}
