"use client";
import {useEffect,useRef,useState} from 'react';
import * as maplibregl from 'maplibre-gl';
import type {FeatureCollection,Point} from 'geojson';
import {request} from '@/lib/api';
import './traffic-signals.css';
type Approach={index:number;bearing:number;label:string;from_side:string;state:string;queue_vehicles:number|null};
type Supply={name:string;asset_id:string;position:number[];distance_m:number;provenance:string;note:string};
type Signal={id:string;name:string;source:string;provenance:string;state:string;note:string;approaches:Approach[];bounds?:number;power_supply?:Supply;controller_id?:string;phase_offset_seconds?:number;cycle_seconds?:number;controller_mode?:string;emergency_stage?:string;verified_priority?:boolean;commands?:{id:string;action:string;status:string}[]};
type SignalData=FeatureCollection<Point,Signal>&{unresolved:{id:string;name:string;group:string}[];metadata:{mapped:number}};
type GoogleOverlay={setMap:(map:unknown)=>void;addListener?:(name:string,fn:()=>void)=>unknown};
type GoogleApi={Marker:new(o:object)=>GoogleOverlay;Polyline:new(o:object)=>GoogleOverlay};
type GoogleMap={addListener:(name:string,fn:(e:{latLng:{lat:()=>number;lng:()=>number}})=>void)=>{remove:()=>void}};
export default function TrafficSignals({map=null,googleMap=null,allowCreate=false}:{map?:maplibregl.Map|null;googleMap?:unknown;allowCreate?:boolean}){
 const [data,setData]=useState<SignalData|null>(null),[error,setError]=useState(''),[actionError,setActionError]=useState(''),[visible,setVisible]=useState(true),[selected,setSelected]=useState(''),[actor,setActor]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [creating,setCreating]=useState(false),[name,setName]=useState(''),[bounds,setBounds]=useState(4),[rotation,setRotation]=useState(0),[position,setPosition]=useState<[number,number]|null>(null);
 const inspector=useRef<HTMLElement>(null),markers=useRef(new Map<string,{remove:()=>void}>());
 useEffect(()=>{if(selected)inspector.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[selected]);
 useEffect(()=>{let alive=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const d=await request<SignalData>('/command/signals',{},30000);if(alive){setData(d);setError('');}}catch{if(alive)setError('Signal state is unavailable; last readings may be stale.');}if(alive)timer=setTimeout(poll,3000);};void poll();return()=>{alive=false;clearTimeout(timer);};},[]);
 useEffect(()=>{const current=markers.current;return()=>{current.forEach(m=>m.remove());current.clear();};},[map,googleMap]);
 useEffect(()=>{
  if(!map&&!googleMap)return;
  const api=(window as unknown as {google?:{maps:GoogleApi}}).google?.maps,keep=new Set<string>();
  if(visible)for(const f of data?.features??[]){const id=f.properties.id;keep.add(id);if(markers.current.has(id))continue;
   const select=()=>{setSelected(id);setNotice('');};
   if(map){const el=document.createElement('button');el.className='traffic-signal-emoji';el.type='button';el.textContent='🚦';el.title=f.properties.name;el.setAttribute('aria-label',`Inspect traffic signal: ${f.properties.name}`);el.onclick=e=>{e.stopPropagation();select();};markers.current.set(id,new maplibregl.Marker({element:el}).setLngLat(f.geometry.coordinates as [number,number]).addTo(map));}
   else if(api){const pin=new api.Marker({map:googleMap,position:{lat:f.geometry.coordinates[1],lng:f.geometry.coordinates[0]},label:{text:'🚦',fontSize:'25px'},icon:{path:'M 0 0',scale:0},title:f.properties.name});pin.addListener?.('click',select);markers.current.set(id,{remove:()=>pin.setMap(null)});}
  }
  for(const [id,m] of markers.current)if(!keep.has(id)){m.remove();markers.current.delete(id);}
 },[map,googleMap,data,visible]);
 useEffect(()=>{if(!creating)return;
  if(map){const click=(e:maplibregl.MapMouseEvent)=>setPosition([e.lngLat.lng,e.lngLat.lat]);map.on('click',click);return()=>{map.off('click',click);};}
  if(googleMap){const listener=(googleMap as GoogleMap).addListener('click',e=>setPosition([e.latLng.lng(),e.latLng.lat()]));return()=>listener.remove();}
 },[creating,map,googleMap]);
 const feature=data?.features.find(f=>f.properties.id===selected),signal=feature?.properties;
 useEffect(()=>{
  const supply=signal?.power_supply;if(!supply||!feature)return;
  const points=[feature.geometry.coordinates,supply.position];
  if(map){const id='selected-signal-supply';map.addSource(id,{type:'geojson',data:{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:points}}});map.addLayer({id,type:'line',source:id,paint:{'line-color':'#aa7415','line-width':3,'line-dasharray':[3,2]}});const el=document.createElement('button');el.className='signal-supply-marker';el.textContent='⚡';el.title=supply.name;const marker=new maplibregl.Marker({element:el}).setLngLat(supply.position as [number,number]).addTo(map);return()=>{marker.remove();if(map.getLayer(id))map.removeLayer(id);if(map.getSource(id))map.removeSource(id);};}
  const api=(window as unknown as {google?:{maps:GoogleApi}}).google?.maps;
  if(googleMap&&api){const line=new api.Polyline({map:googleMap,path:points.map(p=>({lng:p[0],lat:p[1]})),strokeColor:'#aa7415',strokeWeight:2,strokeOpacity:.65});const pin=new api.Marker({map:googleMap,position:{lng:supply.position[0],lat:supply.position[1]},label:'⚡',title:supply.name});return()=>{line.setMap(null);pin.setMap(null);};}
 },[map,googleMap,selected,signal?.power_supply?.asset_id]);
 const act=async(action:string,target:string)=>{setBusy(true);setActionError('');try{await request('/emergency/action',{method:'POST',body:JSON.stringify({action,target,actor,request_id:crypto.randomUUID()})},30000);setData(await request<SignalData>('/command/signals'));setNotice('Controller command committed.');}catch(e){setActionError(e instanceof Error?e.message:'Action not confirmed');}finally{setBusy(false);}};
 const create=async()=>{if(!position)return;setBusy(true);setActionError('');try{const next=await request<SignalData>('/command/signals',{method:'POST',body:JSON.stringify({name,actor,bounds,rotation,lon:position[0],lat:position[1],request_id:crypto.randomUUID()})},60000);setData(next);const added=next.features.find(f=>!data?.features.some(old=>old.properties.id===f.properties.id));setSelected(added?.properties.id??'');setCreating(false);setNotice('Signal and nearest-transformer connection saved to the shared database run.');}catch(e){setActionError(e instanceof Error?e.message:'Signal not saved');}finally{setBusy(false);}};
 return <div className="traffic-signals-control"><button className="signal-toggle" aria-pressed={visible} onClick={()=>setVisible(!visible)}>🚦 Signals {visible?'on':'off'}</button><span>{data?.metadata.mapped??'—'} mapped junctions · click 🚦 for each direction</span>{allowCreate&&<button className="signal-toggle" onClick={()=>{setCreating(!creating);setPosition(null);}}>＋ Create signal</button>}{error&&<p role="alert">{error}</p>}
 {creating&&<section className="signal-inspector"><h3>Create a traffic signal</h3><p>Click its location on the map. Approach bearings describe the direction vehicles travel toward.</p><div className="signal-inspector-grid"><label>Junction name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Approaches<select value={bounds} onChange={e=>setBounds(Number(e.target.value))}>{[2,3,4,6].map(n=><option key={n} value={n}>{n} bound</option>)}</select></label><label>Rotate layout (degrees)<input type="number" min={0} max={359} value={rotation} onChange={e=>setRotation(Number(e.target.value))}/></label><label>Operator<input value={actor} onChange={e=>setActor(e.target.value)}/></label></div><p>{position?`${position[1].toFixed(6)}, ${position[0].toFixed(6)}`:'No map location selected'}</p><p>The nearest distribution transformer will be read from the stored electrical inventory and linked automatically. This is a modeled supply relationship.</p><button disabled={busy||!position||!actor.trim()||name.trim().length<3} onClick={()=>void create()}>Save signal & connect transformer</button><button onClick={()=>setCreating(false)}>Cancel</button></section>}
 {signal&&<section ref={inspector} className="signal-inspector" aria-label="Signal information and operations"><header><div><small>JUNCTION CONTROLLER · {signal.bounds??'—'} APPROACHES</small><h3>🚦 {signal.name}</h3></div><button aria-label="Close signal inspector" onClick={()=>setSelected('')}>✕</button></header><div className="signal-inspector-grid"><div><span>Operating mode</span><strong>{signal.controller_mode??'Unknown'}</strong></div><div><span>Cycle / offset</span><strong>{signal.cycle_seconds??'—'}s / {signal.phase_offset_seconds??'—'}s</strong></div><div><span>Priority</span><strong>{signal.verified_priority?'VERIFIED GREEN':signal.emergency_stage??'No controller'}</strong></div></div>
 <div className="signal-direction-grid">{signal.approaches?.map(a=><article key={a.index} data-state={a.state}><span className="signal-bearing" style={{transform:`rotate(${a.bearing}deg)`}}>↑</span><div><strong>{a.label} · {a.state}</strong><small>From {a.from_side} side · bearing {a.bearing}°</small><small>{a.queue_vehicles??'—'} vehicles queued · simulated</small></div></article>)}</div><p>{signal.note}</p>
 {signal.power_supply&&<div className="signal-supply"><strong>⚡ {signal.power_supply.name}</strong><p>{signal.power_supply.distance_m} m away · {signal.power_supply.provenance}</p><p>{signal.power_supply.note} The map line shows this relationship.</p></div>}
 <div className="signal-operations"><label>Operator name<input aria-label="Signal operator name" value={actor} onChange={e=>setActor(e.target.value)} placeholder="Enter your name"/></label><button disabled={!signal.controller_id||!actor.trim()||busy||!!error} onClick={()=>void act(signal.controller_mode==='MANUAL'?'AUTO':'MANUAL',signal.controller_id!)}>{signal.controller_mode==='MANUAL'?'Return to automatic':'Take manual control'}</button></div>{signal.commands?.filter(c=>c.status==='PENDING').map(c=><div className="signal-command" key={c.id}><span>{c.action.replaceAll('_',' ')}</span><button disabled={!actor.trim()||busy||!!error} onClick={()=>void act('APPLY',c.id)}>Apply command</button></div>)}{!signal.commands?.some(c=>c.status==='PENDING')&&<p>No pending corridor command at this junction.</p>}<footer>{signal.source} · {signal.provenance} position · simulated controller</footer></section>}
 {notice&&<p role="status">{notice}</p>}{actionError&&<p role="alert">{actionError}</p>}<details><summary>{data?.unresolved.length??0} junctions awaiting coordinates</summary><ul>{data?.unresolved.map(j=><li key={j.id}>{j.name}</li>)}</ul></details></div>;
}
